% Copyright 2026 The MathWorks, Inc.

classdef PublishedResultsTest < matlab.unittest.TestCase
    %PublishedResultsTest Compare model results with published U.S. vintages.

    properties
        LWResult
        LWInput
        LWPublishedData
        LWPublishedParameters
        HLWResult
        HLWInput
        HLWPublishedData
        HLWPublishedParameters
    end

    methods (TestClassSetup)
        function estimatePublishedVintages(testCase)
            files = setupPublishedData;

            testCase.LWInput = readtable(files.LW, Sheet="input data", ...
                VariableNamingRule="preserve", TextType="string");
            testCase.LWPublishedData = readtable(files.LW, Sheet="data", ...
                VariableNamingRule="preserve", TextType="string");
            testCase.LWPublishedParameters = readtable(files.LW, ...
                Sheet="parameters", VariableNamingRule="preserve", ...
                TextType="string");
            lwOptions = rstarOptions("LW2023", Verbose=false);
            testCase.LWResult = rstar("LW2023", lwOptions).estimate(testCase.LWInput);
            testCase.verifyEqual(testCase.LWResult.options.SampleStart, ...
                testCase.LWInput.Date(1) + calquarters(8));
            testCase.verifyEqual(testCase.LWResult.options.SampleEnd, ...
                testCase.LWInput.Date(end));

            testCase.HLWInput = readtable(files.HLW, Sheet="US input data", ...
                VariableNamingRule="preserve", TextType="string");
            testCase.HLWPublishedData = readtable(files.HLW, ...
                Sheet="HLW Estimates", VariableNamingRule="preserve", ...
                TextType="string");
            testCase.HLWPublishedParameters = readtable(files.HLW, ...
                Sheet="Parameters", VariableNamingRule="preserve", ...
                TextType="string");
            optimizer = rstar.utils.maximumLikelihoodOptions(ScaleProblem=true);
            options = rstarOptions("HLW2023", SampleStart=datetime(1961, 1, 1), ...
                OptimizationOptions=optimizer, Verbose=false);
            testCase.HLWResult = rstar("HLW2023", options).estimate(testCase.HLWInput);
        end
    end

    methods (Test, TestTags = {'Integration'})
        function testLWMatchesPublishedFilteredAndSmoothedSeries(testCase)
            actual = [ ...
                testCase.LWResult.stage3.rstarFiltered, ...
                testCase.LWResult.stage3.trendFiltered, ...
                testCase.LWResult.stage3.zFiltered, ...
                testCase.LWResult.stage3.outputGapFiltered, ...
                testCase.LWResult.stage3.rstarSmoothed, ...
                testCase.LWResult.stage3.trendSmoothed, ...
                testCase.LWResult.stage3.zSmoothed, ...
                testCase.LWResult.stage3.outputGapSmoothed];
            expected = testCase.LWPublishedData{:, [3:6, 8:11]};

            testCase.verifyEqual(testCase.LWInput.Date(9:end), ...
                testCase.LWPublishedData.Var1);
            testCase.verifyEqual(actual, expected, AbsTol=0.06);
        end

        function testLWMatchesPublishedParameters(testCase)
            expected = testCase.LWPublishedParameters{1, 2:end};
            actual = [ ...
                testCase.LWResult.stage3.theta(1:13)', ...
                testCase.LWResult.stage3.theta(14:16)'];

            testCase.verifyEqual(testCase.LWResult.lambdaG, ...
                testCase.LWPublishedParameters{7, 2}, AbsTol=0.003);
            testCase.verifyEqual(testCase.LWResult.lambdaZ, ...
                testCase.LWPublishedParameters{8, 2}, AbsTol=0.002);
            testCase.verifyEqual(testCase.LWResult.stage3.logLikelihood, ...
                testCase.LWPublishedParameters{6, 2}, AbsTol=0.25);
            testCase.verifyEqual(actual(1:13), expected(1:13), AbsTol=0.02);
            testCase.verifyEqual(actual(14:16), expected(14:16), AbsTol=0.06);
        end

        function testHLWMatchesPublishedFilteredSeriesAndParameters(testCase)
            actual = [ ...
                testCase.HLWResult.stage3.trendFiltered, ...
                testCase.HLWResult.stage3.zFiltered, ...
                testCase.HLWResult.stage3.rstarFiltered, ...
                testCase.HLWResult.stage3.outputGapFiltered];
            expected = testCase.HLWPublishedData{:, [3, 7, 11, 15]};
            publishedParameters = testCase.HLWPublishedParameters{:, 2};
            expectedTheta = [ ...
                publishedParameters(4:8); ...
                publishedParameters(16:18); ...
                publishedParameters(10); ...
                publishedParameters(9); ...
                publishedParameters(11:13)];
            actualTheta = testCase.HLWResult.stage3.theta(1:13);

            testCase.verifyEqual(testCase.HLWInput.date(5:end), ...
                testCase.HLWPublishedData.Var1);
            testCase.verifyEqual(actual, expected, AbsTol=5e-4);
            testCase.verifyEqual(testCase.HLWResult.lambdaG, ...
                publishedParameters(1), AbsTol=5e-4);
            testCase.verifyEqual(testCase.HLWResult.lambdaZ, ...
                publishedParameters(2), AbsTol=5e-4);
            testCase.verifyEqual(abs(actualTheta(6:8)), abs(expectedTheta(6:8)), ...
                AbsTol=5e-4);
            testCase.verifyEqual(actualTheta([1:5, 9:13]), ...
                expectedTheta([1:5, 9:13]), AbsTol=5e-4);
        end

    end
end
