env:
  DOCMAKER_GITHUB_TOKEN: ${{ secrets.DOCMAKER_GITHUB_TOKEN }}

name: Package

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: read

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v3
        with:
          release: R2026b
          products: Econometrics_Toolbox

      - name: Build toolbox
        uses: matlab-actions/run-build@v3
        with:
          tasks: package

      - name: Upload toolbox
        uses: actions/upload-artifact@v7
        with:
          name: Rstar-${{ github.ref_name }}
          path: release/Rstar.mltbx
          if-no-files-found: error
